# IntroduĂ§ĂŁo {#intro}

Imagine se fosse possĂ­vel acessar uma Ăşnica pĂĄgina na internet que centralizasse todas as informaĂ§Ăľes sobre polĂ­tica ambiental no Brasil. A pessoa usuĂĄria visitaria o *website*, faria buscas por polĂ­ticas pĂşblicas, por atos normativos, por unidade federativa ou por ano e baixaria os resultados de sua busca de maneira organizada. De forma fĂĄcil e rĂĄpida, esta pessoa poderia fazer pesquisa cientĂ­fica ou aplicada, escrever artigos jornalĂ­sticos de interesse ambiental ou atĂŠ monitorar a aĂ§ĂŁo de administraĂ§Ăľes pĂşblicas em ĂĄreas sensĂ­veis do Brasil.

Essa é a proposta do Diário do Clima, que busca centralizar essas informaçőes a partir da coleta e filtro nos diários oficiais de todos os 5.570 municípios brasileiros. A equipe da Open Knowledge Brasil já possui experięncia na coleta de Diários Oficiais dos municípios através do Projeto [Querido Diário](https://queridodiario.ok.org.br/) que iniciou em 2019. Nessa etapa, junto com mais sete organizaçőes, organizamos um mecanismo de inteligęncia artificial capaz de separar documentos que tem relaçăo com a temática de meio ambiente e clima, facilitando o acesso de jornalistas e comunicadores e também como forma de facilitar a fiscalizaçăo e cobrança da política ambiental nos municípios.

Estamos felizes em te ver interessadx nesse projeto! Para saber com mais detalhes sobre como tudo isso é feito vocę pode fazer a leitura desse documento na íntegra.

