# O que é o Querido Diário? {#queridodiario}

O Diário Oficial da União (DOU) é um importante veículo de comunicação nacional, criado em 1° de outubro de 1862, sancionado pela Lei Imperial nº 1.177 (54 anos após a chegada da corte portuguesa ao Brasil). Sua função, desde então, é divulgar as leis e normas do país, de forma simples, direta e documental, sem qualquer tipo de contestação ou queixa; em outras palavras, este é o instrumento em que o governo presta contas à sociedade ([Lara, 2011](https://bdtd.ucb.br:8443/jspui/handle/123456789/1336)). Atualmente  o DOU pode ser acessado através do [link da Imprensa Nacional](https://www.gov.br/imprensanacional/pt-br) permitindo buscas por palavras-chave ou buscas avançadas que permitem o filtro por seções, data, títulos ou conteúdo, entre outros. As seções básicas do DOU são:

1. Leis, decretos, resoluções, instruções normativas, portarias e outros atos normativos de interesse geral;
2. Atos de interesse dos servidores da Administração Pública Federal;
3.  Extratos de instrumentos contratuais (acordos, ajustes, autorizações de compra, contratos, convênios, ordens de execução de serviço, termos aditivos e instrumentos congêneres) editais de citação, intimação, notificação e concursos públicos, comunicados, avisos de licitação entre outros atos da administração pública decorrentes de disposição legal.

Por conter tantas informações relevantes, o DOU é utilizado como fonte em diferentes níveis de pesquisa, principalmente para recuperação de informações. [Guerra et al. (2015)](https://www.scielo.br/j/rap/a/cXjcx6hgZ4r5XN3t6rd7SSJ/?lang=en), por exemplo, analisa a resposta das agências reguladoras no combate a COVID-19 através da busca de conteúdo no DOU e também das 11 agências reguladoras no país. Outros estudos contemplam a  análise regulatória de medicamentos no Brasil [(Feitoza-Silva et al., 2017)]( http://dx.doi.org/10.11606/issn.2316-9044.v18i2p122-156) e a inferência sobre risco de fraude nos contratos públicos  [(Lima et al., 2020)](https://aclanthology.org/2020.findings-emnlp.143.pdf).

Embora o DOU receba a maior parte da atenção da pesquisa de atos administrativos no Brasil, a exigência de publicidade de informações não se limita ao Poder Executivo Federal. Outras entes federados (Estados e Municípios) e poderes (Judiciário e Legislativo) também possuem meios próprios de publicação de atos públicos. No entanto, poucos estudos mencionam Diários Oficiais Municipais. [Xavier et al.(2015)](https://www.scielo.br/j/tinf/a/mJmTKbL94hj89q9p8HfCnLj/?format=pdf&lang=pt) propuseram uma arquitetura híbrida de indexação do Diário Municipal de Cachoeiro de Itapemirim - ES. 

O projeto Querido Diário não surgiu do nada, ele veio inspirado pela [Operação Serenata de Amor](https://serenata.ai/) que criou a Rosie, uma robô que através de inteligência artificial consegue rastrear irregularidades nos gastos do Congresso Nacional. E também do [Open Data Index](https://ok.org.br/projetos/open-data-index/) A OKBR já tinha uma ideia de acessibilizar os diários oficiais e com tantas outras conquistas foi possível aproveitar o conhecimento acumulado para criar o projeto Querido Diário. Atualmente, a equipe da OKBR também atua em outros projetos e desde o início da pandemia da COVID-19 foram realizados projetos voltados para solucionar problemas relacionados a transparênca de dados públicos principalmente relacionados à saúde, como por exemplo o projeto [Sorria #Estamos Vigiando](https://ok.org.br/projetos/sorria-estamosvigiando/), o [Monitor da INDA](https://ok.org.br/inda/) e a [Transparência COVID-19](https://transparenciacovid19.ok.org.br/).

Em resumo, o projeto _Querido Diário_ busca **mapear, coletar e processar todos os diários municipais do país e disponibilizá-los em formato aberto para a sociedade civil**. Para realizar essas três tarefas, a Open Knowledge Brasil conta com uma equipe de pessoas cientistas e engenheiras de dados e uma grande comunidade de pessoas colaboradoras voluntárias.

## Status

Para mapear diários oficiais municipais e extrair informações relevantes foi necessário compreender qual é a dimensão e escopo de um diário oficial municipal. Segundo o [Diário Oficial do município de São Paulo](http://www.docidadesp.imprensaoficial.com.br/Busca.aspx) o jornal é dividido em oito seções: Gabinete do Prefeito, Secretarias, Servidores, Concursos, Editais, Licitações, Câmara Municipal e Tribunal de Contas.
O que é visto na prática é que um diário municipal está, teoricamente, categorizado em algumas seções que correspondem a exigências legais de publicação de atos públicos. Contudo, como os municípios não seguem padrão uniforme de divulgação de informações, essas seções podem não ter títulos comuns ou mesma estrutura ou nem serem publicadas em todos os diários - afinal, nem sempre todos os atos públicos cuja publicação é exigida por lei ocorrem todos os dias. De modo geral, as seções obrigatórias são:

- Atos Normativos: Obrigações ou direitos aos cidadãos fruto de atividade do poder executivo (ou legislativo) municipal. 
- Atos de Pessoal: Mudanças nas atividades dos funcionários municipais, contemplando ingresso em carreira pública, exoneração, concessão de afastamento temporário, etc.
- Contas Públicas: Obrigações de dívida dos municípios e peça orçamentária em respeito à LRF.
- Audiências Públicas: Informes para a população sobre audiências públicas referentes à atividade do governo municipal e implementação de políticas públicas locais.
- Licitações: Informes sobre os principais instrumentos de contratação de bens e serviços privados no Brasil pelo setor público.
- Processos Disciplinares: Informes de processos investigativos e disciplinares sobre conduta de servidores públicos ou contratantes do poder executivo municipal.
- Processos Tributários: Informes de acórdãos entre o fisco municipal e os contribuintes em processos administrativos tributários que afetam a arrecadação do município.
- Conselhos Municipais: Informes sobre a fiscalização de políticas públicas por parte da sociedade civil.

O Querido Diário, atualmente, compila os diários oficiais de todos os municípios brasileiros através de inteligência artifical. O projeto possui código aberto, ou seja, qualquer pessoa pode contribuir no projeto ou entender como a lógica é arquitetada. De maneira simplificada os diários oficias são coletados dos seus respectivos endeços eletrônicos e submetidos a raspadores (_spiders_) em que filtram o resultado para extrair informações como o formato do arquivo, tamanho e ser convertido em um documento acessível de PDF. Concomitantemente, são extraídas outras informações do arquivo como data, seção do diário que são armazenadas em uma base de metadados. Duas fontes são origem do processo: o  arquivo bruto onde extraem-se o texto em formato TXT em formato aberto e os metadados onde é realizado uma busca textual com o mecanismo de busca de análise de dados ElasticSearch, onde é poss?vel indexar as informações dos diários e armazená-las centralmente facilitando futuras buscas. Após isso, uma interação entre os indexadores do ElasticSearch e o texto puro é realizada passando estes dados para a Interface de Programação de Aplicações (API) (usado pela máquina) que é integrada a uma [platadorma de visualização](https://queridodiario.ok.org.br/) para o usuário.

Atualmente, quase todos os diários dos 5.570 municípios brasileiros já foram mapeados pela nossa comunidade. Isto significa que sabemos onde esses diários são publicados, qual sua cobertura temporal e qual o tipo de arquivo em que estes diários são publicados.

Destes municípios, nós também já temos raspadores de diários para mais de 2.300 municípios, cerca de 41% do total. Disponibilizamos esses dados via API aberta ao público, disponível aqui. Por necessidade de verificação dos dados coletados, estão disponíveis na API apenas diários de 13 capitais brasileiras.

Com relação ao processamento do texto dos diários, nós já somos capazes de converter qualquer formato de diário (PDF, Docx, RTF, HTML, JPEG, etc.) em .txt e fazer a extração e validação de CPFs e CNPJs dos diários oficiais. Contudo, ainda há muito o que fazer em termos de extração de informação não-estruturada e sua subsequente estruturação.

### Próximos passos

Como o interesse da sociedade civil por conteúdo de diários oficiais normalmente é focado em um tema, a segmentação do diário surge como nossa primeira prioridade de ciência de dados, uma vez que nos permitiria "fatiar" o conteúdo e permitir buscas apenas em seções desejadas. Portanto, uma tarefa fundamental para a equipe da OKBR seria uma forma automatizada de segmentação do diário em diferentes categorias de interesse, iniciando nos temas de meio ambiente e clima.
