# O que é o Diário do Clima? {#diariodoclima}

O projeto Diário do Clima nasceu quando a OKBR venceu um edição de inovação jornalística promovido pelo _Google News Initiative_. O Diário do Clima em como objetivo monitorar os atos oficiais relativos a meio ambiente e clima publicados diariamente nos diários oficiais de municípios brasileiros. A proposta foi desenvolvida em conjunto com outras sete organizações -- [((o))Eco](https://oeco.org.br/), [Eco Nordeste](https://agenciaeconordeste.com.br/), [Agência Envolverde](https://envolverde.com.br/), [InfoAmazonia](https://infoamazonia.org/), [ClimaInfo](https://climainfo.org.br/), [#Colabora](https://projetocolabora.com.br/) e [Política por Inteiro](https://www.politicaporinteiro.org/), tendo pessoas jornalistas como público-alvo deste projeto.

A estrutura do Diário do Clima é a mesma do Querido Diário (QD), pois é possível aplicar algumas das técnicas previamente utilizadas no QD para extração de informações (o tratamento do texto extraído, a busca por palavras-chave, o filtro por cidade e período temporal, etc.). O maior desafio deste projeto, contudo, seria selecionar os diários oficiais que tenham informações relevantes no âmbito do jornalismo ambiental e climático. Enquanto que o QD permite buscas de conteúdo sem restrição temática, este projeto busca apenas extrair conteúdo de um tema. Isto exige que concentremos as buscas por intervalo de texto, seções e palavras que indiquem o início e o fim de uma busca textual. Por exemplo, precisamos ser capazes de buscar e retornar resultados que digam respeito ao "Código Florestal Brasileiro" vs. "Código de Trânsito Brasileiro" usando as palavras de cada sentença de busca, a distância entre elas e a indicação se elas aparecem simultaneamente em um diário ou não.

Além disso, os conteúdos de interesse devem estar identificados no texto e categorizados por "entidades" relevantes (em computação, trata-se de um "objeto" ou conceito — por exemplo, "infração ambiental", "licitação" ou "CNPJ") aos quais estão relacionados. A ideia é que seja possível agrupar atos diferentes que têm relação com o mesmo assunto/tipo de publicação. Este filtro e categorização devem ser realizados diariamente para serem consumidos pela equipe de curadoria jornalística e pela plataforma.

## Contribuições do Diário do Clima ao Querido Diário

O trabalho desenvolvido neste projeto expandirá o alcance e funcionalidades do Querido Diário de várias formas. A primeira delas é o cruzamento de bases de dados com conteúdo extraído dos diários, que permitirá:
+ O enriquecimento do documento com reconhecimento de entidades (assuntos, tipos de publicação);
+ A conexão com a base de dados da Receita Federal, para que seja possível adicionar elementos sobre as empresas (sócios, por exemplo), sempre que um CNPJ for identificado na publicação de interesse.

Outra novidade que será desenvolvida e adicionada à API do QD é a opção de retornar, dos diários, apenas os trechos de conteúdo relacionados a uma temática predefinida (nesse caso, a temática ambiental) para realização de um filtro. As "entidades" (agrupamentos semânticos) encontradas nos trechos de conteúdo também devem ser adicionadas à resposta, e assim seria possível pesquisar dados da receita com entidades de CNPJ, por exemplo. Essa nova funcionalidade da API será fundamental para a geração de bases de dados que serão  consumidas por pessoas usuárias avançadas do QD.

Finalmente, a API do QD nas cidades desejadas diariamente, ativando o filtro por temática. A plataforma agruparia os atos pelas entidades encontradas e buscaria os dados da Receita Federal na própria API para cada entidade -- possibilitando, assim, que atos relevantes sejam analisados com mais profundidade pelos jornalistas, além da produção de relatórios e da criação de alertas ou notificações para usuários.
