# Política Ambiental no Brasil {#politica-ambiental}

A [Constituição Federal](https://www.planalto.gov.br/ccivil_03/Constituicao/Constituicao.htm) é o principal documento legislativo brasileiro, ou lei suprema. O Brasil é um Estado Democrático de Direito sendo que a União, os Estados, o Distrito Fedral e os municípios são todos autônomos no termo da constituição. Conforme o Art.24 da Constituição Federal de 1988 (CF/88),inexistindo lei federal sobre normas gerais cabe ao Estado fazer o papel legislativo e atender a essas peculiaridades. O Art. 30 especifica que os municípios legislam sobre assuntos de interesse local e suplementam a legislação federal e estadual no que couber. Portanto, cabe à União legislar sobre normas gerais ao passo que Estados e Municípios legislem sobre assuntos de interesse local e suplementem a legislação federal no que couber. Para entender política ambiental no Brasil é importante conhecer as principais iniciativas e atos normativos no âmbito federal para que seja possível identificar, no nível municipal, quais ações e atos administrativos possam ser encontrados nos Diários Oficiais. A política ambiental no país, contudo, não está restrita à CF/88 e abaixo discutimos alguns dos grandes marcos ambientais que tem impacto até hoje.

## Cenário geral

Dentro da política ambiental, ao longo da história, houve muitas conquistas no que diz respeito a aceitação a pluralidade institucional para a resolução de problemas ambientais. A [Lei dos Crimes Ambientais de 1998](https://www.planalto.gov.br/ccivil_03/LEIS/L9605.htm), por exemplo, regulamente sobre as penas decorrentes a crimes ambientais cometidos no território brasileiro, além das modificaçãoes e inovações propostas no código florestal a partir de 1965.  bem como as Políticas Nacional de Meio Ambiente (1981), Mudança Climática (2009) e Resíduos Sólidos (2012) instituídas ao longo de meados do século XX e início do século XXI representaram mudanças institucionais no que diz respeito ao que compreende meio ambiente. Mesmo assim, anteriormente a este período as legislações federais regulamentavam a área, regras de exploração, era muito metódico e concentrado na esfera federal. A Constituição Federal de 1988 que prevê um meio ambiente ecologicamente equilibrado e possui um artigo exclusivamente dedicado à temática ambiental (225), abriu caminho para a formalização do que é praticado atualmente um Estado Federado onde existem três competências: Federal, Estadual e Municipal, que podem tanto exercer administrativamente ou legislativamente.

A gestão pública é divida pelas competência nos três níveis podendo essas competências serem privativas, exclusivas, residuais, concorrentes e comuns. No que tange à questão ambiental a União, Estados e Municípios possuem competências concorrentes, conservando o princípios da predominância de interesse. Existem alguns temas que são competência exclusiva da União, como por exemplo o controle do transporte marítimo e fluvial, caso haja conflitos de competência eltes serão resolvidos no poder judiciário.  A defesa ambiental envolve muitos atores com diversos interesses associações civis, dentre eles as empresas privadas, representações locais, empresas e sindicatos, organizações do regime de governança global e de organizações civis transnacionais, assim como governos locais, regionais e nacional, e representantes institucionais de interesses difusos (no caso do Brasil, o Ministério Público) [(Neves, 2012)](https://www.scielo.br/j/ea/a/LKBmWppgNLLyCdHphwrMb5d/?format=pdf&lang=pt).

O município é o único ator estatal capaz de modelar a ocupação do território por deter a prerrogativa exclusiva do planejamento estratégico do território municipal através do Plano Diretor, destinação de áreas à urbanização pela delimitação da zona
urbana, promoção de determinados usos do solo em caráter exclusivo ou em conjunto com outros usos, definição da relação entre espaços livres e construídos, determinação da densidade habitacional e licenciamento da localização de atividades econômicas.

Quanto aos assuntos de competência municipal exclusiva, destacam-se: o transporte coletivo, a coleta e tratamento de resíduos sólidos urbanos, o saneamento básico que tradicionalmente engloba os serviços de abastecimento de água, a coleta e o tratamento de esgotos domésticos, drenagem de águas pluviais, pavimentação, gestão de resíduos sólidos domésticos e urbanos, iluminação pública, trânsito em área urbana, estradas vicinais, mercados, feiras, matadouros, segurança urbana, higiene, assistência social, esporte, lazer e recreação (Meirelles, 2001, p.407s).

## Código Florestal Brasileiro (Leis 23.793/34, 4.771/65 e 12.651/12)

O Código Florestal tem que estar sempre se atualizando e adaptando-se a realidade ambiental, econômica e social do país. O primeiro documento (1934) priorizava a regulamentação da terra, instituía regras sobre a exploração econômica de espaços que poderiam ter riscos para a fauna e flora brasileira. Em 1965 já se estabelecia Áreas de Preservação Permanente e Reserva Legal nas propriedades rurais, mas ainda deixava a ação pública centralizada no âmbito federal. A partir da Criação da Política Nacional do Meio Ambiente (1981) e Contituição Federal (1988) observou-se a necessidade de uma descentralização da governança ambiental, então além da manutenção e revisão das APPs, RL, foram também incluídas regras sobre as áreas de Uso Restrito (AUR), sobre o Cadastro Ambiental Rural (CAR), onde os produtores rurais devem fazer obrigatoriamente seu cadastro e passando concorrentemente para Estados e os municípios muitas das competências legislativas e administrativas que antes eram concentradas em âmbito federal. Outra inovação do Código Florestal de 2012 foi a inclusão do licenciamento ambiental e também sobre a exploração florestal.


## Política Nacional do Meio Ambiente (Lei n° 6.938/81)

A segunda grande iniciativa em política ambiental, contudo, é anterior à CF/88. A [Política Nacional do Meio Ambiente (PNMA)](https://www.planalto.gov.br/ccivil_03/LEIS/L6938.htm) foi aprovada em 1981 e dispõe sobre atividades que preservem, melhorem e recuperem o meio ambiente de modo a proporcionar à população brasileira melhores condições de desenvolvimento social e econômico. A PNMA previu a formulação de planos e órgãos atendendo aos princípios de ação governamental, racionalização, planejamento, proteção, controle e zoneamento das atividades, proteção e educação (Art. 2°) que orientassem a União, Estados, Distrito Federal, Territórios e Municípios no que se relaciona com a preservação da qualidade ambiental e manutenção do equilíbrio ecológico. Para o cumprimento dos objetivos foi criado em 1990 o Sistema Nacional de Meio Ambiente (SISNAMA), que é um conglomerado de órgãos públicos responsável pela proteção ambiental no Brasil. O SISNAMA é composto por:

- Órgão superior: Conselho do governo (assessora diretamente o Presidente da República)
- Órgão consultivo e deliberativo: Conselho Nacional do Meio Ambiente (Conama) (sendo o Presidente o Ministro do Meio Ambiente)
- Órgão central: Secretaria do Meio Ambiente (Atualmente Ministério do Meio Ambiente)
- Órgãos executores: Instituto Brasileiro de Meio Ambiente e dos Recursos Naturais Renováveis (IBAMA) e Instituto Chico Mendes de Conservação da Biodiversidade (ICMBio)
- Órgãos seccionais: órgãos ou entidades estaduais responsáveis pela execução de programas, projetos e pelo controle e fiscalização de atividades capazes de provocar a degradação ambiental.
-Órgãos locais: órgãos ou entidades municipais, responsáveis pelo controle e fiscalização dessas atividades, nas suas respectivas jurisdições.

A fim de cumprir os objetivos dispostos na PNMA é necessário ter instrumentos para realizar as atividades. De maneira geral, a PNMA é dividida em três grandes instrumentos, sejam:

### Instrumentos Econômicos
* Incentivos econômicos como o Fundo Nacional do Meio Ambiente e diferentes financiamentos do BNDES
* Inibidores econômicos como o ICMS, a taxa de reposição florestal, a Taxa de Controle e Fiscalização Ambiental (TCFA), e o Fundo Nacional de Desenvolvimento Florestal

_ainda falta escrever o texto_
### Instrumentos que Regulam a Ocupação do Espaço
* Licenciamento que integra o Estudo de Impacto Ambiental, a Análise de risco, o Plano de recuperação de áreas degradadas (para atividades com alto impacto ambiental/mineração), a Avaliação Ambiental, Viabilidade ambiental e Cadastro Técnico Federal
* Conservação: Sistema Nacional de Unidades de Conservação, Corredores Ecológicos, Programa Piloto para a Proteção das Florestas Tropicais do Brasil (PPG7), restrição ao uso de recursos naturais nas propriedades privadas (Lei n° 4.771/65 e Resoluções do CONAMA), recuperação ambiental, auto suprimento e reposição florestal. 
* Zoneamento ambiental: Zoneamento ecológico-econômico e ambiental e a avaliação de impacto ambiental. Este plano define as unidades ambientais em termos de área para uso intensivo, extensivo, de preservação e de uso múltiplo.Neste âmbito existem os planos diretores dos municípios que são a nível local e do estado, a nível regional. Muitas vezes não tem acesso.

### Instrumentos Punitivos
* Punição: Lei dos Crimes Ambientais, Decreto Lei n° 6.514 de 22 de julho de 2008, Código Florestal
Lei de Crimes Ambientais, PF/MPF órgão de combate ambiental.
Adicionalmente, Lei n° 9.605/98 que instituiu a Lei de Crimes Ambientais prevê penas para pessoas físicas ou jurídicas relacionados à fauna, flora, poluição, ordenamento urbano e administração ambiental.
Multas

A PNMA não deixa claro como cooperar interfederalmente nos estados federados, nem na CF [(Leme, 2010)](http://repositorio.ipea.gov.br/bitstream/11058/3992/2/PPP_n35_Municipios.pdf); essa é uma das grandes críticas dentro da gestão pública ambiental, além da grande diversidade de problemas específicos em cada município, conhecido como Federalismo assimétrico [(Neves, 2012)](https://www.scielo.br/j/ea/a/LKBmWppgNLLyCdHphwrMb5d/?format=pdf&lang=pt). Além disso, a falta de capacidade técnica e infraestrutura  dos municípios para lidar com a gestão ambiental, bem como disponibilidade de recursos, marcos legais e órgãos ambientais locais influi no tipo de gestão ambiental que será promovida nos diferentes municípios.

#### - Esses órgãos podem fiscalizar a adoção de ações municipais relativas ao meio ambiente?
Sim, mas atualmente o fluxo é ação municipal > estadual> federal. A ação federal pode ser mais necessária para casos graves de risco ambiental, de interesse econômico/ social, ou que sejam de competência exclusiva da União, como por exemplo qualquer corrente de água em pelo menos dois diferentes estados, ou que venham de outro país, o mar territorial, recursos minerais, cavidades naturais, sítios arqueológicos, terras indígenas, potenciais de energia hidráulica. O município de Atafona (RJ) é um local onde é necessária a presença de órgão federal para conter os efeitos do avanço do mar na cidade.

#### - Eles editam normativos que devem ser seguidos pelos municípios? - Existe exigência para que municípios criem suas próprias secretarias ambientais?
Não exatamente, o que acontece são delegações/ adaptações da Lei, a não ser que a Lei mude. É o caso da [Lei Complementar n° 140/11](https://www.planalto.gov.br/ccivil_03/Leis/LCP/Lcp140.htm#art20), por exemplo, que rege alguns intrumentos para a cooperação entre União, Estados e Municípios, como a criação de Comissões Tripartites para promover a cooperação da gestão pública ambiental, integração... Além disso, é instituído mais detalhadamente as competência da União, Estados e Municípios para fazerem a melhor gestão pública ambiental concorrentemente. De maneira geral, aos Estados compete cumprir a PNMA e outras Políticas Nacionais relacionadas ao ambiente, formular e cumprir a Política Estadual de Meio Ambiente, realizar zoneamento e licenciamento ambiental e fiscalizar as atividades. Aos municípios, também compete o cumprimento das Políticas Nacionais e Estaduais Ambientais, formular e cumprir a Política Municipal de Meio Ambiente e realizar licenciamento e fiscalização. Entretanto, não é observado na prática que todos os municípios tenham políticas ambientais ou órgãos competentes para esta atividade (embora não seja regulamentado a exigência de secretarias/conselhos).

#### - Existem ações ou programas em conjunto com governos municipais?
Não exatamente. O que acontece são Leis/delegações a serem cumpridas, mas também a União fornece serviços que podem ser utilizados para a gestão municipal, como é o caso do Sistema Nacional de Unidades de Conservação (SNUC) utilizado para preservação ambiental e proteção das espécies ameaçadas. E outros que estão elencados mais a frente, como o Cidades+Verdes, dentre outros. No entanto, não são ações diretas, mas auxiliares para ajudar na gestão ambiental, como organização de base de dados, sistemas georreferenciais, dentre outros. As ações ou programas diretos poderiam ser encontradas a nível mais específico para resolução de problemas, suponho.

## Estatuto da Cidade (Lei 10.257/01)

A Lei n° 10.257/01 denominada [Estatuto da Cidade](https://www.planalto.gov.br/ccivil_03/Leis/LEIS_2001/L10257.htm) prevê a criação de instrumentos para a política urbana de municípios no que diz respeito ao desenvolvimento urbano. No âmbito municipal, se prevê instrumentos como Plano Diretor, zoneamento ambiental, planejamento participativo, estudo de impacto ambiental e urbano, plano plurianual e diretrizes orçamentárias. O próprio Estatuto estabelece obrigatoriedade do Plano Diretor para municípios acima de 20 mil habitantes, ou que sejam instâncias turísticas, interesse econômico/social, municípios metropolitanos ou que estejam sob risco natural ou de outra natureza. O Plano Diretor é essencial pois  define o espaço urbano da cidade e possui as diretrizes orçamentárias. Além disso, para aqueles municípios com risco ambiental é obrigatório que o plano diretor contenha planos de mitigação e adaptação urbana quanto ao uso e ocupação do solos. Para aquelas cidades que não possuem Plano Diretor é previsto no estatuto o direito à cidades sustentáveis com minimização de risco ambiental. Portanto, é dever da cidade atentar-se também ao meio ambiente, concedendo licenças ambientais, aplicando taxas e utilizando dos intrumentos de competência municipal.

## Política Nacional de Mudança do Clima (Lei n° 12.187/09)

A PNMC visa o desenvolvimento econômico sustentável com foco em redução da pobreza e desigualdades sociais. O objetivo da PNMC é mitigar os danos ambientais através de ações de mitigação e adaptação nos âmbitos local, regional e nacional. A PNMC adota como compromisso nacional voluntário as reduções de gases de efeito estufa entre 36,1% e 38,9% até 2020.

Os instrumentos da _PNMC_ consistem, principalmente, dos Planos Nacionais de Mudança do Clima e nas ações de prevenção de incêndios e medidas fiscais e tributárias destinadas a reduzir as emissões. Adicionalmente, estão previstas linhas de crédito (AASSUMPCAO: de quem e para o quê?), de financiamento e pesquisas (de quem? CNPq?) que criaram indicadores de sustentabilidade como registros, inventários, estimativas, avaliações, dentre outros. Finalmente, foram criados instrumentos institucionais como a Rede Brasileira de Pesquisas sobre Mudanças Climáticas Globais (Rede Clima) e o Comitê Interministerial de Mudança do Clima, entre outros.

O Decreto nº 9.578/2018, entre outras ações, detalha os instrumentos da _PNMC_ para cumprimento do compromisso voluntário brasileiro. Para efeito da regulamentação são considerados o Plano de Ação para a Prevenção e Controle do Desmatamento na Amazônia Legal (PPCDAM), o Plano de Ação para a Prevenção e Controle do Desmatamento e das Queimadas no Cerrado (PPCerrado), o Plano Decenal de Expansão de Energia (PDE), o Plano para Consolidação de uma Economia de Baixa Emissão de Carbono na Agricultura (Plano ABC) e o Plano de Emissões da Siderurgia, Plano de Mineração, Plano Indústria, Plano Setorial de Transporte e Mobilidade Urbana, Plano Setorial da Saúde para Mitigação e Adaptação à Mudança do Clima (PSMC).

Segundo [ABEMA](https://www.abema.org.br/images/publicacoes/2020_10_27-Cartilha.pdf) Belo Horizonte, Extrema, Feira de Santana, Fortaleza, Manaus, Palmas, Porto Alegre, Recife, Rio de Janeiro, São Paulo, entre outros municípios brasileiros possuem Política Municipal sobre Mudanças Climáticas. Palmas adotou em 2003. Em termos de planos, João Pessoa possui Plano de Ação Climática e outras cidades que também possui algum plano ou estratégia para combater as mudanças climáticas e tem como objetivo redução de Gases de Efeito Estufa.

(AASSUMPCAO: dê o exemplo o melhor destes planos).

#### - Quais são as medidas mais importantes do PNMC? Os municípios aderiram? 
Políticas Municipais de Mudanças Climáticas acredito que seja um dos marcos mais importantes. Municípios aderiram.

#### - Quais são as principais iniciativas implementadas no âmbito municipal que promovam os objetivos do PNMC?
#### - Existem exigências municipais para a certificação de baixo impacto ambiental para grandes obras?
A princípio, não vi exatamente. O liceciamento ambiental, em si, já administra certo tipo de impacto, a partir da exigência de viabilidade, estudo de impacto, etc. Além das taxas para ter permissão de taxas com alto grau de uso e alto npivel de potencial poluidor.

## Política Nacional de Resíduos Sólidos (Lei n° 12.305/10)

Reúne o conjunto de princípios, objetivos, instrumentos, diretrizes, metas e ações adotados pelo Governo Federal, isoladamente ou em regime de cooperação com Estados, Distrito Federal, Municípios ou particulares, com vistas à gestão integrada e ao gerenciamento ambientalmente adequado dos resíduos sólidos. Articula-se também com a Política Nacional de Educação Ambiental e Política Federal de Saneamento Básico (Lei n° 11.445/07). Possui as definições de termos de rejeitos, coleta seletiva, área contaminada, área órfã, etc, e também os instrumentos, obejetivos e diretrizes da política. Possui o Plano Nacional de Resíduos Sólidos para avançar a agenda, também incluindo os planos estaduais, intermunicipais e municipais.

A PNRS estabelece que é obrigatório aos municípios a elaboração de Plano Municipal de Gestão Integrada de Resíduos Sólidos, até 02 de agosto de 2012, sendo esta uma condição para o Distrito Federal e os Municípios terem acesso a recursos da União destinados a empreendimentos e serviços relacionados à limpeza urbana e ao manejo de resíduos sólidos, ou para serem beneficiados por incentivos de entidades federais de crédito ou fomento para tal finalidade. Além disso, exige-se o cumprimento dos planos em vigência para usufruiur dos recursos [MMA](https://antigo.mma.gov.br/cidades-sustentaveis/residuos-solidos/instrumentos-da-politica-de-residuos/planos-municipais-de-gest%C3%A3o-integrada-de-res%C3%ADduos-s%C3%B3lidos.html).

(AASSUMPCAO: dê o exemplo o melhor destes planos).

## Competências da União (ou Federais)

A União ainda possui muita importância no que diz respeito a conservação e controle do desmatamento da Amazônia e também na gestão das Unidades de Conservação, por isso criou em 200 a partir da Lei n° 9.985 o Sistema Nacional de Unidades de Conservação que também precisa dos municípios e estados para manter as informações atualizadas.

**- Órgãos federais**

Na sequência estão alguns órgãos federais cruciais para a gestão ambiental brasileira. Além destes também existem outros órgãos como a Agência Nacional de Águas (ANA) e o Instituto Brasileiro de Desenvolvimento Florestal (IBDF).

_Ministério do Meio Ambiente_: Em 1992 foi criado o [Ministério do Meio Ambiente (MMA)](https://www.gov.br/mma/pt-br/acesso-a-informacao/institucional) como um dos marcos da Rio-92 (Eco-92),  o IBAMA, ICMBio e também recentemente adicionado pelo [decreto n° 10.455 de 2020](https://www.in.gov.br/en/web/dou/-/decreto-n-10.455-de-11-de-agosto-de-2020-271717699) o Instituto de Pesquisas Jardim Botânico do Rio de Janeiro (JBRJ são entidades vinculadas ao MMA. A [Lei n° 12.187 de 2009](https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2009/lei/l12187.htm) instituiu a Política Nacional de Mudança do Clima (PNMC), sendo esta atualmente supervisionada pelo MMA. Os Fundos Nacionais do Meio Ambiente e de Mudança do Clima são gerenciados atualmente pelo MMA, sendo este o órgão superior do governo.

_IBAMA_: Poder de polícia ambiental, responsável por recolher e repassar recursos da TCFA, Imposto Territorial Rural, Cadastro Ambiental Rural. Seus objetivos institucionais são relativos ao licenciamento ambiental, ao controle da qualidade ambiental, à autorização de uso dos recursos naturais e à fiscalização, monitoramento e controle ambiental e ações supletivas de competência da União, conforme legislação ambiental. Zoneamento e avaliação de impacto ambiental e Cadastro Técnico Federal.

*Serviços, impostos e taxas vinculadas ao IBAMA*:
- CAR: Cadastro Ambiental Rural é o registro público eletrônico de âmbito nacional, obrigatório para todos os imóveis rurais, com a finalidade de integrar as informações ambientais das propriedades e posses rurais referentes às Áreas de Preservação Permanentes (APP), Áreas de Uso Restrito (AUR), Reserva Legal (RL), de remanescentes de florestas e demais formas de vegetação nativa, e das áreas consolidadas, compondo base de dados para controle, monitoramento, planejamento ambiental e econômico e combate ao desmatamento.
- ITR: O CAR gera créditos tributários por meio de deduções na base  de cálculo do Imposto Territorial Rural
- PRA: Programa de Apoio e Incentivo à Conservação do Meio Ambiente e aos Programas de Regularização Ambiental 
- CTF: Cadastro Técnico Federal  identifica as pessoas físicas e jurídicas sob controle ambiental e fiscalização ambiental, conforme previsto em legislação federal ou de âmbito nacional, gerando informações para a gestão ambiental no Brasil.
- TCFA: Taxa de Controle e Fiscalização Ambiental é um tributo para controle e fiscalização das atividades potencialmente poluidoras e utilizadoras de recursos naturais

_ICMBio_:  Tem como função apresentar e editar normas e padrões de gestão de Unidades de Conservação (UC) federais; propor a criação, regularização fundiária e gestão das UC federais; e apoiar a implementação do Sistema Nacional de Unidades de Conservação (SNUC). Este órgãos contribui para a recuperação de áreas degradadas em UC. Fiscaliza e aplica penalidades administrativas ambientais ou compensatórias aos responsáveis pelo não cumprimento das medidas necessárias à preservação ou correção da degradação ambiental. Monitora o uso público e a exploração econômica dos recursos naturais nas UC onde isso for permitido, obedecidas as exigências legais e de sustentabilidade do meio ambiente. geração e disseminação sistemática de informações e conhecimentos relativos à gestão de UCs, da conservação da biodiversidade e do uso dos recursos faunísticos, pesqueiros e florestais.  Contribui para a implementação do Sistema Nacional de Informações sobre o Meio Ambiente (Sinima) e aplica, no âmbito de sua competência, dispositivos e acordos internacionais relativos à gestão ambiental. Elabora o Relatório de Gestão das UC.

_Instituto de Pesquisa Jardim Botânico do Rio de Janeiro (JBRJ)_: É uma autarquia federal criada pela [Lei n° 10.316/2001](https://www.planalto.gov.br/ccivil_03/leis/leis_2001/l10316.htm), sua missão é realizar e difundir pesquisas relacionadas à flora brasileira com foco na conservação da biodiversidade. Sua estrutura é de pesquisa e este órgão responde diretamente ao MMA.

## Competências Estaduais

As entidades estaduais são geralmente as Secretarias Estaduais de Meio Ambiente e os Ministérios Públicos estaduais. Os órgãos estaduais podem ser acessados no site do [IBAMA](https://www.ibama.gov.br/flora-e-madeira/descentralizacao-da-gestao-florestal/competencias-do-ibama-e-dos-orgaos-estaduais-de-meio-ambiente). A principal diferença do órgão estadual é que pode fomentar mais iniciativas no Âmbito dos municípios a partir da criação de políticas ambientais e de clima. Os órgãos estaduais tem poder de legislar sobre a obrigatoriedade da criação de Comitês, Fóruns e Secretarias ambientais nos municípios e transferir recursos para o desenvolvimento dessa agenda. A criação de órgãos ambientais representam já um passo a frente para o compromisso da agenda ambiental brasileira e mundial.

Em 2019, durante a Conferência Brasileira de Mudança do Clima, os 26 estados e o Distrito Federal ratificaram a [Carta](https://www.abema.org.br/noticias/258-conferencia-brasileira-de-mudanca-do-clima-6-a-8-11-2019-recife-pe) dos Órgãos Estaduais de Meio Ambiente pelo Clima, que firma 17 compromissos em torno da ação climática. 

A implantação do ICMS ecológico (Paraná, Rio de Janeiro  e +16)  fomenta a criação de Fundo Municipal de Meio Ambiente, cONSELHO, ÓRGÃO ADMINISTRATIVO E GUARDA MUNICIPAL PARA REPARTIÇÃO DOS RECURSOS ver [aqui](https://www.ceperj.rj.gov.br/wp-content/uploads/2021/08/Boletim-1-ICMS-Ecologico-1.pdf). No RJ é feito o Índice de Qualidade do Sistema Municipal de Meio Ambiente (IQSMMA), que destina uma parcela de bonificação em todos os indicadores que compõem os cálculos dos relativos utilizados para a composição do Índice Final de Conservação Ambiental (IFCA), do município habilitado. Além de todos os programas ambientais que são de âmbito federal tem que estar regularizado para receber o recurso.  

Em questionário realizado pela GIZ (2020) 12 estados (Acre, Amazonas, Ceará, Espírito Santo, Maranhão, Minas Gerais, Pará, Paraíba, Pernambuco, Rio de Janeiro, São Paulo e Sergipe) e o Distrito Federal. Planos de reflorestamento, unidades de conservação e orçamento para a governança do clima são presentes em mai de 70% dos estados. Por outro lado, menos que 40% tem incentivos fiscais para atividades sustentáveis, metas de redução de gases de efeito estufa, captação de recursos nacionais e internacionais ou precificação de carbono. Além disso, muitos estados apresentam Planos ABC Estaduais que promovem a agricultura de baixa emissão de carbono. Além disso, a criação das Comissões Técnicas Tripartites que objetivam manter diálogo entre União, Estados e municípios  (carecem de maior institucionalização no marco legal, mas ajudam) [(Leme, 2010)](http://repositorio.ipea.gov.br/bitstream/11058/3992/2/PPP_n35_Municipios.pdf).

Existem outras iniciativas feitas pelas entidades estaduais, é o caso do Estado do Ceará que criou o Selo Verde promovendo o fortalecimento da gestão ambiental municipal, com o fomento da criação de órgãos municipais [(Leme, 2010)](http://repositorio.ipea.gov.br/bitstream/11058/3992/2/PPP_n35_Municipios.pdf).No estado do Tocantins, foi criado o "Guia Prático - Criação do Fórum Municipal Lixo & Cidadania" a partir da Secretaria Estadual do Meio Ambiente e Recursos Hídricos (Semarh) que foi uma iniciativa para difundir a criação de Fóruns Municipais para lidar com a coleta de resíduos sólidos. Veja a [notícia](https://conexaoto.com.br/2022/01/10/secretaria-de-meio-ambiente-apoia-municipios-na-criacao-do-forum-municipal-lixo-e-cidadania).

## Competências Municipais

Em 1988 na cidade de Curitiba/PR foi criada a [Associação Nacional de Órgãos Municipais de Meio Ambiente (Anamma)](https://www.anamma.org.br/quem-somos) que tem como objetivo o fortalecimento dos Sistemas Municipais de Meio Ambiente (SISMUMAs) para desenvolver políticas, ações, planos, participação ativa em Conselhos Estaduais e no CONAMA. Atualmente são parceiros algumas ONGs nacionais e internacionais, bem como associações de conselhos municipais e estaduais.

A gestão das Unidades de Conservação representam importância para o município por conter planos de manejo obrigatórios, bem como a presença de zonas de amortecimento que são externas aos limites da UC que tem por objetivo amenizar os efeitos ambientais que possam prejudicar a UC. A fiscalização das Zonas de amortecimento das UCs é principalmente incumbência municipal [(Neves, 2012)](https://www.scielo.br/j/ea/a/LKBmWppgNLLyCdHphwrMb5d/?format=pdf&lang=pt).

Segundo [Leme, 2010](http://repositorio.ipea.gov.br/bitstream/11058/3992/2/PPP_n35_Municipios.pdf) cada município tem diferentes demandas,no entanto, todos devem cumprir a legislação ambiental Federal e Estadual. A autora ainda frisa a importância da transferência direta de recursos para o desenvolvimento de Secretarias e conselhos municipais de meio ambiente, já que a transferência de recursos são voluntárias por meio de convênios e não pela obrigatoriedade da existência de uma Secretaria ou Conselho municipal como acontece nas políticas de saúde e assistência social. Mesmo assim, é previsto transferência e captação de recursos provenientes de ICMS Ecológico, taxas de licenciamento, multas, pagamento por serviços ambientais, doações dentre outros, passível da criação de um conselho, secretaria ou órgão ambiental municipal. O Fundo Nacional de Meio Ambiente regulado pela Lei [7.797/89](https://www.planalto.gov.br/ccivil_03/Leis/L7797.htm) institui que o Fundo deve ser repassado entidades Estaduais e Municipais que tenham como objetivos a preservação do ambiente e proteção da fauna e flora, com projetos na temática das UC, recuperação de áreas degradadas, controle ambiental, dentre outros. Sendo que não poderá ser tranferido à órgãos que possuam fins lucrativos. 

De maneira geral é incumbência municipal fiscalizar, autuar e licenciar atividades relacionadas ao ambiente, bem como prover assistência técnica e reposição florestal, sendo estas atividades divididas com o Estado, a depender dos limites territoriais da atividade. Para o caso de municípios menores existe ainda a possibilidade de trabalhar em parcerias como foi o caso da região do Vale do Ribeira em São Paulo que formou o Consórcio de Segurança Alimentar e Desenvolvimento Local (Consad) [(Leme, 2010)](http://repositorio.ipea.gov.br/bitstream/11058/3992/2/PPP_n35_Municipios.pdf)

A [ABEMA - Associação Brasileira de Entidades Estaduais de Meio Ambiente](https://www.abema.org.br/images/publicacoes/2020_10_27-Cartilha.pdf) explica em um fluxograma como é o funcionamento da criação de uma nova política pública relacionada à mudança climática em estados e municípios. A priori, é necessário que haja a neessidade de criação da Política Pública e é previsto que ele não seja de competência exclusiva da União, não havendo esse empecilho é necessário que a natureza da Política Pública seja de natureza concorrente à União e o Estado ou Município que está propondo a criação. Ainda é possível criar a Lei caso haja uma legislação a respeito do tema, mas ele não esteja suficientemente claro. Caso contrário, o Estado ou Município não poderá criar a Política Pública, em termos gerais, no que diz respeito ao meio ambiente os estados e municípios possuem muita autonomia para propor ações e regras sobre o meio ambiente e clima prevalecendo, no âmbito administrativo, o federalismo cooperativo ambiental, onde há atividades coordenadas entre União, Estados e Municípios.

O artigo de [Sanches e Neto, 2017](https://periodicos.uninove.br/geas/article/viewFile/10056/4749) aponta sobre as iniciativas realizadas nos municípios do Mato Grosso do Sul, onde destacam-se palestras de educação ambiental, incentivos para feiras de orgânicos e estabelecimento de exigências quanto ao desempenho ambiental de empresas. Por outro lado, poucos projetos visavam a coleta de resíduos sólidos ou saneamento, indicando ainda uma alta precariedade e miscelânea de objetivos para o cumprimento das Políticas Ambientais a nível municipal. Outro ponto importante é a participação da sociedade Civil, o [relato](https://florestal.revistaopinioes.com.br/revista/detalhes/20-governanca-ambiental-nos-municipios/) do Paulo que foi Secretário do Meio Ambiente em Extrema (MG) contou que o município  foi primeiro lugar em 2010 no índice Mineiro de Responsabilidade Social (IMRS) e que as reuniãos com ONGs, comitês e parceria com estado, União e empresas privadas foram essenciais. Dentre as ações no município foi realizada a Agenda 21 Local, o Programa Municpal de Resíduos Sólidos (1995) e Licenciamento Ambiental a partir de 2006, para empreendimentos potencialmente poluidores de impacto local, além disso, o projeto Conservador das Águas traalhou com pagamentos por serviços ambientais (PSA) nas sub-bacias hidrográficas da região.

## Programas Federais Implementados pelos Municípios Brasileiros

Existem programas que são diretamente para os municípios:
- Programa Nacional de Capacitação de Gestores Municipais
- Cidades+verdes: criado o Cadastro Ambiental Urbano (CAU), para mapeamento e divulgação de informações sobre essas áreas.
- Programa Nacional de Recuperação de áreas Contaminadas

No âmbito geral os municípios tem autonomia para elaborar suas políticas sem entrar em conflito com as legislaçãoes federal e estadual, como acontece nas políticas de meio ambiente, mudança climática e resíduos sólidos. Existem muitas iniciativas também com relação a produção de alimentos orgânicos.

## Cooperação Internacional

A promoção de acordos internacionais é essencial para a proteção da fauna e flora visando o desenvolvimento sustentável brasileiro. Existem muitos projetos municipais que possuem financiamentos internacionais , como foi o Mecanismo de Desenvolvimento Limpo (MDL). Este programa fomentou a criação de iniciativas inovadoras no combate das ações climáticas em investimentos de projetos de energias renováveis, como a Usina Hidrelétrica de Jirau, em Porto Velho (RO), ou aterros sanitários em Paulínia (SP). Ao todo, cerca de 179 projetos beneficiaram diretamente os municípios brasileiros e contribuíram para compromissos internacionais de mitigação climática. Portanto, a cooperação internacional é essencial para a promoção da sustentabilidade e de execução dos planos ambientais.

O marco mais importante em política internacional ambiental foi, contudo, a realização da Conferência das Nações Unidas sobre o Meio Ambiente e Desenvolvimento (1992), conhecida por Eco-92, que inaugurou as conferências sobre mudanças climáticas no mundo. Dentre seus principais resultados, aponta-se a elaboração da Agenda 21, que focava no compromisso com a responsabilidade ambiental e a criação da Convenção para a Biodiversidade.  Atualmente existem muitos municípios que possuem Agendas 21 locais e que já revisam seus planos e propõem a Agenda 2030.

As regiões Sudeste e Nordeste são as que detinham de maiores experiências de Agenda 21 até o ano de 2002, ao todo 69 municípios no Nordeste e 72 no Sudeste. A título de exemplo, o município de São Paulo foi a primeira capital a iniciar o processo de [construção da Agenda 21](http://www.capital.sp.gov.br/cidadao/rua-e-bairro/meio-ambiente/agenda-21-local) em 1992 tendo como principal objetivo subsidiar a política e gestão ambientais e urbanas. O município de Santos e Rio de Janeiro iniciaram seus processos nos anos 1994 e 1997. Destacam-se na construção das Agendas 21 Locais, a criação de Fóruns e Conselhos para execução das ações, a principal limitação das agendas analisadas foram a falta de experiência em orçamento participativo e também a limitação deste [Kohler, 2003](https://www.teses.usp.br/teses/disponiveis/6/6134/tde-19052005-111222/publico/Maria_Claudia_Kohler_diss). Atualmente o orçamento participativo é mais comum dentro da gestão pública.

A Eco-92 se diferenciou por ter uma grande presença de chefes de Estado e ONGs e apesar de não promover ações diretas para a mitigação e adaptação do clima, gerou uma alta repercussão em âmbito mundial, nacional e também local. Após a Eco-92 que foi criado o Ministério do Meio Ambiente no Brasil. O [Decreto n° 10.455 de 11/08/2020](https://www.in.gov.br/en/web/dou/-/decreto-n-10.455-de-11-de-agosto-de-2020-271717699) aprova a estrutura regimental do MMA, sendo imprescindível a permanência e manutenção de relações e estratégias internacionais. À Secretaria-executiva do MMA deve supervisionar e coordenar os programas com financimanentos de organismos internacionais, dos projetos e convênios. Ao Departamento de Relacões Internacionais do MMA compete propor diretrizes de política externa, desenvolver estratégias de apoio às políticas ambientais brasileiras.

O [Acordo de Paris](http://www.planalto.gov.br/ccivil_03/_Ato2015-2018/2017/Decreto/D9073.htm), é outro exemplo em que é marco ambiental. Ele foi promulgado em 2017 foi estabelecido sob a Convenção-Quadro das Nações Unidas sobre Mudança do Clima, em 12 de dezembro de 2015 e firmado em Nova Iorque, em 22 de abril de 2016. Um dos principais objetivos é manter média global bem abaixo de 2ºC em relação aos níveis pré-industriais, sendo isso uma ação muito desafiadora. O acordo de Paris representou um marco para as ações climáticas com estabelecimentos de metas mais concretas, representa também conjugação com a PNMC.



